theme = "blowfish"
# baseURL = "https://your_domain.com/"
defaultContentLanguage = "de"

# pluralizeListTitles = "true" # hugo function useful for non-english languages, find out more in  https://gohugo.io/getting-started/configuration/#pluralizelisttitles

enableRobotsTXT = true
summaryLength = 25

buildDrafts = false
buildFuture = false

enableEmoji = true

# Use git info to set "date" and "lastmod" for each article automatically.
enableGitInfo = true
[frontmatter]
date = [':git', ':authorDate']
lastmod = [':git', ':fileModTime']

# googleAnalytics = "G-XXXXXXXXX"

[pagination]
  pagerSize = 100

[imaging]
  anchor = "Center"

[sitemap]
  changefreq = "daily"
  filename = "sitemap.xml"
  priority = 0.5

[outputs]
  home = ["HTML", "RSS", "JSON"]

[related]
  threshold = 0
  toLower = true
  includeNewer = true

    [[related.indices]]
        name = "topics"
        weight = 100
