repos:
  - repo: https://github.com/errata-ai/vale
    rev: v3.9.1
    hooks:
      - id: vale
        args: ["--glob", "!archetypes/**"]
  - repo: https://github.com/codespell-project/codespell
    rev: v2.3.0
    hooks:
    - id: codespell
      files: ^.*\.(jl|md|yaml)$
      args: ["--ignore-words=.codespell-ignore-words.txt"]

ci:  # https://pre-commit.ci/
  autofix_prs: false
  autoupdate_schedule: weekly
